config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/tasks', to: 'tasks#index'

  # Create
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  # Read one
  get '/tasks/:id', to: 'tasks#show', as: :show_task

  # Update
  get '/tasks/:id/edit', to: 'tasks#edit'
  patch '/tasks/:id', to: 'tasks#update', as: :task

  # Delete
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/:id
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks
  def create
    task = Task.new(tasks_params)
    tasks.save
  end

  def edit
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class=“formulaire”>
 <%= form_for(@task) do |f| %>
   <%= f.text_field :title %>
   <%= f.text_field :details %>
   <%= f.submit %>
 <% end %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

  <% @tasks.each do |task| %>

    <input type="checkbox" name="details" <%= 'checked' if task.completed == true %>>
    <label for="details"><%= link_to task.title, show_task_path(task) %></label>

  <% end %>

app/views/tasks/new.html.erb
<form class="pure-form">
    <fieldset>
        <legend>Enter Your New task</legend>

        <input type="text" placeholder="Title">
        <input type="text" placeholder="Details">

        <label for="remember">
            <input id="remember" type="checkbox"> Remember me
        </label>

        <button type="submit" class="pure-button pure-button-primary">Update</button>
    </fieldset>
</form>

app/views/tasks/show.html.erb
<h2> <%= @task.title %></h2>
<p> <%= @task.details %></p>
<p> <%= @task.completed %></p>

<p><%= link_to 'Back to List', tasks_path %></p>